name: Supabase Backup

on:
  schedule:
    - cron: "0 3 * * *"  # todo dia às 03:00 UTC
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Run backup
        env:
          PGPASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          pg_dump -4 \
            -h ${{ secrets.DB_HOST }} \
            -U postgres.postgres.koqkdqrcuplhtjggvora \
            -d postgres \
            --no-owner \
            --format=custom \
            --file=backup.dump \
            "sslmode=require"

      - name: Compress backup
        run: gzip backup.dump

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: supabase-backup
          path: backup.dump.gz
